### ISSUE TITLE
error running test: Error: Cannot find module 'hubot-test-helper'

### ISSUE THREAD

**Issue by MonicaG** [mtsmfm/hubot-test-helper#23]
Hi,

I am getting the following error when I try to run my test.  It appears to be an issue with version 1.4 as I was able to run on 1.3. 

Here is the error I get:

```
module.js:339
    throw err;
    ^

Error: Cannot find module 'hubot-test-helper'
  at Function.Module._resolveFilename (module.js:337:15)
  at Function.Module._load (module.js:287:25)
  at Module.require (module.js:366:17)
  at require (module.js:385:17)
  at Object.<anonymous> (/Users/monica/development/mozilla/webqabot/test/test_webqa.coffee:1:10)
  at Object.<anonymous> (/Users/monica/development/mozilla/webqabot/test/test_webqa.coffee:1:1)
  at Module._compile (module.js:435:26)
  at Object.loadFile (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:311:12)
  at Module.require (module.js:366:17)
  at require (module.js:385:17)
  at /usr/local/lib/node_modules/mocha/lib/mocha.js:216:27
  at Array.forEach (native)
  at Mocha.loadFiles (/usr/local/lib/node_modules/mocha/lib/mocha.js:213:14)
  at Mocha.run (/usr/local/lib/node_modules/mocha/lib/mocha.js:453:10)
  at Object.<anonymous> (/usr/local/lib/node_modules/mocha/bin/_mocha:393:18)
  at Module._compile (module.js:435:26)
  at Object.Module._extensions..js (module.js:442:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:311:12)
  at Function.Module.runMain (module.js:467:10)
  at startup (node.js:136:18)
  at node.js:963:3
```

Here are the first few lines of my test:
```javascript
Helper = require('hubot-test-helper')
helper = new Helper('../scripts/webqa.coffee')
chai = require 'chai'
expect = chai.expect
```

I invoke my test from the command line by doing the following:
```
mocha --compilers "coffee:coffee-script/register" test/test_webqa.coffee
```

My package.json has the following, which will install hubot-test-helper version 1.4 
```json
 "devDependencies": {
    "chai": "^3.4.1",
    "hubot-test-helper": "^1.3.0",
    "mocha": "^2.3.4",
    "coffee-script": "^1.9.3"
  }
```

However, if I change my package.json to explicitly use version 1.3, then my tests run and pass.  Example:

```json
"devDependencies": {
    "chai": "^3.4.1",
    "hubot-test-helper": "1.3.0",
    "mocha": "^2.3.4",
    "coffee-script": "^1.9.3"
  }
```

**Comment by mdelagrange** [comment]
@kengz: it looks like the 1.4.0 gem is missing the /lib directory that was supposed to be part of a `prepublish` step.

**Comment by kengz** [comment]
Had no idea it wasn't working properly since the Travis CI passed. I propose we write more robust tests to move on. @mdelagrange do we need to add the gem file manually?

**Comment by mtsmfm** [comment]
Sorry, I forgot to update semantic-release script... :sweat_drops: 
I'm fixing it now. I hope it fixed by d6b43d8.

**Comment by mtsmfm** [comment]
Hmm, I got something wrong :dizzy_face: 
prepublish run automatically before `npm publish`

**Comment by mtsmfm** [comment]
I added compiled file at this time.
Please tell me your problem is fixed or not :smile:

**Comment by benrudolph** [comment]
had the same issue and then updated and works fine now. thank you!

i'm on: `"hubot-test-helper": "^1.4.3"`

**Comment by mtsmfm** [comment]
:star2:

**Comment by MonicaG** [comment]
Yes, it works for me using version 1.4.3.  Thank you!
